name: CI

on:
  push:
  workflow_dispatch:

jobs:
  IaC:
    name: "Infrastructure as Code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        run: |
          cd function/
          npm ci 
          npm test
          
      - name: deploy
        run: |
          terraform init
          terraform validate